# Generated by Django 5.1.3 on 2024-12-22 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvpat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='membership_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='president',
            name='membership_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
