# Generated by Django 5.1.3 on 2024-12-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvpat', '0002_director_membership_num_president_membership_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_num',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
