# Generated by Django 5.1.3 on 2025-01-17 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvpat', '0003_alter_user_membership_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='directors_id',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='president_id',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='random_num',
        ),
        migrations.AddField(
            model_name='voter',
            name='directors_vote',
            field=models.ManyToManyField(blank=True, to='vvpat.director'),
        ),
        migrations.AddField(
            model_name='voter',
            name='president_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vvpat.president'),
        ),
    ]
