# Generated by Django 5.1.3 on 2025-01-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvpat', '0004_remove_voter_directors_id_remove_voter_president_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='president',
            name='membership_num',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
