# Generated by Django 5.1.3 on 2025-01-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvpat', '0005_alter_president_membership_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
