# Generated by Django 5.1.3 on 2025-01-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvpat', '0006_voter_is_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='directors_vote',
        ),
        migrations.AlterField(
            model_name='voter',
            name='president_vote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='directors_vote',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
