# Generated by Django 5.1.1 on 2025-02-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvpat', '0007_remove_voter_directors_vote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='omr_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='president',
            name='omr_vote',
            field=models.BooleanField(default=False),
        ),
    ]
