# Generated by Django 5.1.1 on 2025-02-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvpat', '0008_director_omr_vote_president_omr_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='omr_votes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='president',
            name='omr_votes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
