# Generated by Django 5.1.1 on 2025-02-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vvpat', '0009_director_omr_votes_president_omr_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='omr_vote',
        ),
        migrations.RemoveField(
            model_name='president',
            name='omr_vote',
        ),
    ]
