# Generated by Django 5.1.1 on 2025-02-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvpat', '0010_remove_director_omr_vote_remove_president_omr_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (0, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
    ]
