# Generated by Django 5.1.1 on 2025-02-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvpat', '0011_alter_user_gender_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
