# Generated by Django 5.1.1 on 2025-02-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvpat', '0012_alter_director_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
